/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciadorreunioes.visao;

import gerenciadorreunioes.controle.LoginControl;
import gerenciadorreunioes.modelo.Servidor;
import javax.swing.JOptionPane;

/**
 *
 * @author alunos
 */
public class GerenciarSenhaGUI extends javax.swing.JFrame {

    private Servidor ser;
    private String senha;
    private int tipo;

    public String getSenha() {
        return senha;
    }

    public GerenciarSenhaGUI() {
        initComponents();
        tipo = 0;
        jLabelSenhaAtual.setVisible(false);
        jPasswordFieldSenhaAtual.setVisible(false);
    }

    public GerenciarSenhaGUI(Servidor ser) {
        initComponents();
        tipo = 1;
        this.ser = ser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelConfirmarSenha = new javax.swing.JLabel();
        jLabelSenhaNova = new javax.swing.JLabel();
        jPasswordFieldConfirmarSenha = new javax.swing.JPasswordField();
        jPasswordFieldSenhaNova = new javax.swing.JPasswordField();
        jLabelSenhaAtual = new javax.swing.JLabel();
        jPasswordFieldSenhaAtual = new javax.swing.JPasswordField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gerenciar Senha", 2, 0, new java.awt.Font("Dialog", 0, 18))); // NOI18N
        jPanel1.setLayout(null);

        jLabelConfirmarSenha.setText("Confirme a nova senha:");
        jPanel1.add(jLabelConfirmarSenha);
        jLabelConfirmarSenha.setBounds(10, 110, 360, 18);

        jLabelSenhaNova.setText("Digite a nova senha:");
        jPanel1.add(jLabelSenhaNova);
        jLabelSenhaNova.setBounds(10, 50, 360, 18);
        jPanel1.add(jPasswordFieldConfirmarSenha);
        jPasswordFieldConfirmarSenha.setBounds(10, 130, 360, 28);

        jPasswordFieldSenhaNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldSenhaNovaActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordFieldSenhaNova);
        jPasswordFieldSenhaNova.setBounds(10, 70, 360, 28);

        jLabelSenhaAtual.setText("Digite a senha atual:");
        jPanel1.add(jLabelSenhaAtual);
        jLabelSenhaAtual.setBounds(10, 170, 360, 18);
        jPanel1.add(jPasswordFieldSenhaAtual);
        jPasswordFieldSenhaAtual.setBounds(10, 190, 360, 28);

        jButtonCancelar.setText("Cancelar");
        jPanel1.add(jButtonCancelar);
        jButtonCancelar.setBounds(210, 240, 120, 30);

        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonConfirmar);
        jButtonConfirmar.setBounds(60, 240, 120, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordFieldSenhaNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldSenhaNovaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldSenhaNovaActionPerformed

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        confirmaMudanca();
        this.dispose();
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void confirmaMudanca() {
        if (tipo == 0) {
            boolean igual = verificaSenhasIguais();
            if (igual) {
                senha = jPasswordFieldSenhaNova.getText();
                LoginControl.preencheSenhaNova(senha);
            } else {
                JOptionPane.showMessageDialog(this, "As Senhas Não Correspondem !!!");
            }
        } else {
            boolean igual = verificaSenhaAtual();
            if (igual) {
                boolean correspondem = verificaSenhasIguais();
                if (correspondem){
                    senha = jPasswordFieldSenhaNova.getText();
                    LoginControl.preencheSenhaNova(senha);
                } else {
                    JOptionPane.showMessageDialog(this, "As Senhas Não Correspondem !!!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "A Senha Atual Está Incorreta !!!");
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarSenhaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarSenhaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarSenhaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarSenhaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarSenhaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JLabel jLabelConfirmarSenha;
    private javax.swing.JLabel jLabelSenhaAtual;
    private javax.swing.JLabel jLabelSenhaNova;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldConfirmarSenha;
    private javax.swing.JPasswordField jPasswordFieldSenhaAtual;
    private javax.swing.JPasswordField jPasswordFieldSenhaNova;
    // End of variables declaration//GEN-END:variables

    private boolean verificaSenhasIguais() {
        boolean igual = false;
        String senhaNova = jPasswordFieldSenhaNova.getText();
        String confirmaSenha = jPasswordFieldConfirmarSenha.getText();
        if (senhaNova.equals(confirmaSenha)) {
            igual = true;
        }
        return igual;
    }

    private boolean verificaSenhaAtual() {
        boolean igual = false;
        String senhaAtualBanco = ser.getSenha();
        String senhaAtualTextArea = LoginControl.criptografar(jPasswordFieldSenhaAtual.getText());
        if (senhaAtualBanco.equals(senhaAtualTextArea)) {
            igual = true;
        }
        return igual;
    }
}
