/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciadorreunioes.visao;

import gerenciadorreunioes.controle.LoginControl;
import gerenciadorreunioes.controle.ServidorControl;
import gerenciadorreunioes.modelo.Servidor;
import javax.swing.JOptionPane;

/**
 *
 * @author alunos
 */
public class GerenciarSenhaGUI extends javax.swing.JFrame {

    private GerenciarServidoresGUI telaServidor;
    private ServidorControl servidorControl;
    private Servidor servidor;
    private int tipo;

    public GerenciarSenhaGUI(Servidor serAux, GerenciarServidoresGUI telaServidor) {
        initComponents();
        servidorControl = new ServidorControl();
        this.telaServidor = telaServidor;
        this.servidor = serAux;
        for (Servidor serv : servidorControl.getServidores()) {
            // se o servidor já existe (está cadastrado no banco)
            if (serv.getSiape().equals(serAux.getSiape())) {
                tipo = 1;
            }
        }
        if (tipo != 1) {
            tipo = 0;
            jLabelSenhaAtual.setVisible(false);
            jPasswordFieldSenhaAtual.setVisible(false);
        }
        servidor.setSerCoordenador(0);
        servidor.setSerDe(0);
        servidor.setSerResponsavelAta(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelConfirmarSenha = new javax.swing.JLabel();
        jLabelSenhaNova = new javax.swing.JLabel();
        jPasswordFieldConfirmarSenha = new javax.swing.JPasswordField();
        jPasswordFieldSenhaNova = new javax.swing.JPasswordField();
        jLabelSenhaAtual = new javax.swing.JLabel();
        jPasswordFieldSenhaAtual = new javax.swing.JPasswordField();
        jButtonConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gerenciar Senha", 2, 0, new java.awt.Font("Dialog", 0, 18))); // NOI18N
        jPanel1.setLayout(null);

        jLabelConfirmarSenha.setText("Confirme a nova senha:");
        jPanel1.add(jLabelConfirmarSenha);
        jLabelConfirmarSenha.setBounds(10, 110, 360, 18);

        jLabelSenhaNova.setText("Digite a nova senha:");
        jPanel1.add(jLabelSenhaNova);
        jLabelSenhaNova.setBounds(10, 50, 360, 18);
        jPanel1.add(jPasswordFieldConfirmarSenha);
        jPasswordFieldConfirmarSenha.setBounds(10, 130, 360, 28);

        jPasswordFieldSenhaNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldSenhaNovaActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordFieldSenhaNova);
        jPasswordFieldSenhaNova.setBounds(10, 70, 360, 28);

        jLabelSenhaAtual.setText("Digite a senha atual:");
        jPanel1.add(jLabelSenhaAtual);
        jLabelSenhaAtual.setBounds(10, 170, 360, 18);
        jPanel1.add(jPasswordFieldSenhaAtual);
        jPasswordFieldSenhaAtual.setBounds(10, 190, 360, 28);

        jButtonConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/download (1).jpg"))); // NOI18N
        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonConfirmar);
        jButtonConfirmar.setBounds(150, 240, 120, 36);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordFieldSenhaNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldSenhaNovaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldSenhaNovaActionPerformed

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        confirmaMudanca();
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void confirmaMudanca() {
        if (tipo == 0) {
            boolean igual = verificaSenhasIguais();
            if (igual) {
                servidor.setSenha(LoginControl.criptografar(jPasswordFieldSenhaNova.getText()));
                servidorControl.adiciona(servidor);
                telaServidor.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "As Senhas Não Correspondem !!!");
            }
        } else {
            boolean igual = verificaSenhaAtual();
            if (igual) {
                boolean correspondem = verificaSenhasIguais();
                if (correspondem) {
                    servidor.setSenha(LoginControl.criptografar(jPasswordFieldSenhaNova.getText()));
                    servidorControl.atualiza(servidor);
                    telaServidor.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "As Senhas Não Correspondem !!!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "A Senha Atual Está Incorreta !!!");
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JLabel jLabelConfirmarSenha;
    private javax.swing.JLabel jLabelSenhaAtual;
    private javax.swing.JLabel jLabelSenhaNova;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldConfirmarSenha;
    private javax.swing.JPasswordField jPasswordFieldSenhaAtual;
    private javax.swing.JPasswordField jPasswordFieldSenhaNova;
    // End of variables declaration//GEN-END:variables

    private boolean verificaSenhasIguais() {
        boolean igual = false;
        String senhaNova = jPasswordFieldSenhaNova.getText();
        String confirmaSenha = jPasswordFieldConfirmarSenha.getText();
        if (senhaNova.equals(confirmaSenha)) {
            igual = true;
        }
        return igual;
    }

    private boolean verificaSenhaAtual() {
        boolean igual = false;
        String senhaAtualBanco = servidor.getSenha();
        String senhaAtualTextArea = LoginControl.criptografar(jPasswordFieldSenhaAtual.getText());
        System.out.println("\n\n " + senhaAtualBanco
        + "\n\n " + senhaAtualTextArea);
        if (senhaAtualBanco.equals(senhaAtualTextArea)) {
            igual = true;
        }
        return igual;
    }
}
