/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciadorreunioes.visao;

import javax.swing.JOptionPane;

/**
 *
 * @author Alunos
 */
public class TelaPrincipalServidorComumGUI extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalNova
     */
    /*
    MODIFICAR A PARTIR DAQUI !!!!! 
    SE FOR RESPONSAVEL POR ATA, INICIALIZA O CONSTRUTOR COM PARAMETRO
    SE NAO, INICIALIZA COM CONSTRUTOR SEM PARAMETRO !!!
     */
    public TelaPrincipalServidorComumGUI() {
        initComponents();
        jMenuItemRedigirATA.setEnabled(false);
    }

    public TelaPrincipalServidorComumGUI(int i) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jToolBar2 = new javax.swing.JToolBar();
        jButtonImprimirAta = new javax.swing.JButton();
        jButtonMudaStatusATA = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuATAs = new javax.swing.JMenu();
        jMenuItemMudarStatusATA = new javax.swing.JMenuItem();
        jMenuItemImprimirATA = new javax.swing.JMenuItem();
        jMenuItemRedigirATA = new javax.swing.JMenuItem();
        jMenuSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciador de Reuniões");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jToolBar2.setRollover(true);

        jButtonImprimirAta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/imprimir-simbolo-interface-de-uma-maquina-impressora_318-67390.jpg"))); // NOI18N
        jButtonImprimirAta.setFocusable(false);
        jButtonImprimirAta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonImprimirAta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButtonImprimirAta);

        jButtonMudaStatusATA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/images.png"))); // NOI18N
        jButtonMudaStatusATA.setFocusable(false);
        jButtonMudaStatusATA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonMudaStatusATA.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonMudaStatusATA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMudaStatusATAActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonMudaStatusATA);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sair.png"))); // NOI18N
        jButtonSair.setText("SAIR");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jMenuATAs.setText("ATAs");

        jMenuItemMudarStatusATA.setText("Mudar Status da ATA");
        jMenuItemMudarStatusATA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMudarStatusATAActionPerformed(evt);
            }
        });
        jMenuATAs.add(jMenuItemMudarStatusATA);

        jMenuItemImprimirATA.setText("Imprimir ATA");
        jMenuItemImprimirATA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemImprimirATAActionPerformed(evt);
            }
        });
        jMenuATAs.add(jMenuItemImprimirATA);

        jMenuItemRedigirATA.setText("Redigir ATA");
        jMenuItemRedigirATA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRedigirATAActionPerformed(evt);
            }
        });
        jMenuATAs.add(jMenuItemRedigirATA);

        jMenuBar1.add(jMenuATAs);

        jMenuSobre.setText("Sobre");
        jMenuSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSobreMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(jButtonSair))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemImprimirATAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemImprimirATAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemImprimirATAActionPerformed

    private void jMenuSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSobreMouseClicked
         JOptionPane.showMessageDialog(this, "Desenvolvido por World Systems \n Desenvolvedores: Hernane Marcos de Faria Júnior \n Igor Ribeiro da Silva \n Técnico em Informática III - IFMG Formiga");
    }//GEN-LAST:event_jMenuSobreMouseClicked

    private void jMenuItemMudarStatusATAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMudarStatusATAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemMudarStatusATAActionPerformed

    private void jButtonMudaStatusATAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMudaStatusATAActionPerformed
        new RedigirAtaGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonMudaStatusATAActionPerformed

    private void jMenuItemRedigirATAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRedigirATAActionPerformed
        new RedigirAtaGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemRedigirATAActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        this.dispose();
        new LoginGUI().setVisible(true);
    }//GEN-LAST:event_jButtonSairActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonImprimirAta;
    private javax.swing.JButton jButtonMudaStatusATA;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenuATAs;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemImprimirATA;
    private javax.swing.JMenuItem jMenuItemMudarStatusATA;
    private javax.swing.JMenuItem jMenuItemRedigirATA;
    private javax.swing.JMenu jMenuSobre;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables

}
