/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciadorreunioes.visao;

import gerenciadorreunioes.controle.LoginControl;
import gerenciadorreunioes.modelo.Servidor;
import javax.swing.JOptionPane;

/**
 *
 * @author Alunos
 */
public class TelaPrincipalCoordenadorGUI extends javax.swing.JFrame {

    private Servidor coordenador;

    public TelaPrincipalCoordenadorGUI() {
        initComponents();
        coordenador = LoginControl.retornaServidorLogado();
        if (coordenador.getSerDe() == 1){
            jLabelCoordenador.setText("Bem vindo(a), Diretor(a) de Ensino " + coordenador.getNome() + "!");
        } else {
            jLabelCoordenador.setText("Bem vindo(a), Coordenador(a) " + coordenador.getNome() + "!");
        }
        if (coordenador.getSerResponsavelAta() == 0) {
            jMenuItemRedigirAta.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButtonGerenciarGrupos = new javax.swing.JButton();
        jButtonGerenciarServidores = new javax.swing.JButton();
        jButtonGerenciarReunioes = new javax.swing.JButton();
        jButtonGerenciarAlunos = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        jButtonMudarStatusAta = new javax.swing.JButton();
        jButtonBuscarAta = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelCoordenador = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuGerenciar = new javax.swing.JMenu();
        jMenuItemGerenciarGrupos = new javax.swing.JMenuItem();
        jMenuItemGerenciarServidores = new javax.swing.JMenuItem();
        jMenuItemGerenciarReunioes = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuATAs = new javax.swing.JMenu();
        jMenuItemMudarStatusAta = new javax.swing.JMenuItem();
        jMenuItemConsultaAta = new javax.swing.JMenuItem();
        jMenuItemRedigirAta = new javax.swing.JMenuItem();
        jMenuSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Tela Principal de Coordenador - Gerenciador de Reuniões");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(560, 415));
        setResizable(false);

        jToolBar1.setRollover(true);

        jButtonGerenciarGrupos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/grupos.jpg"))); // NOI18N
        jButtonGerenciarGrupos.setToolTipText("Gerenciar Grupos");
        jButtonGerenciarGrupos.setFocusable(false);
        jButtonGerenciarGrupos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGerenciarGrupos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonGerenciarGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerenciarGruposActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonGerenciarGrupos);

        jButtonGerenciarServidores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/servidores.jpg"))); // NOI18N
        jButtonGerenciarServidores.setToolTipText("Gerenciar Servidores");
        jButtonGerenciarServidores.setFocusable(false);
        jButtonGerenciarServidores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGerenciarServidores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonGerenciarServidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerenciarServidoresActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonGerenciarServidores);

        jButtonGerenciarReunioes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/reunioes.png"))); // NOI18N
        jButtonGerenciarReunioes.setToolTipText("Gerenciar Reuniões");
        jButtonGerenciarReunioes.setFocusable(false);
        jButtonGerenciarReunioes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGerenciarReunioes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonGerenciarReunioes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerenciarReunioesActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonGerenciarReunioes);

        jButtonGerenciarAlunos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/alunos.png"))); // NOI18N
        jButtonGerenciarAlunos.setToolTipText("Gerenciar Alunos");
        jButtonGerenciarAlunos.setFocusable(false);
        jButtonGerenciarAlunos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGerenciarAlunos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonGerenciarAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerenciarAlunosActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonGerenciarAlunos);

        jToolBar2.setRollover(true);

        jButtonMudarStatusAta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/status.png"))); // NOI18N
        jButtonMudarStatusAta.setToolTipText("Mudar Status da Ata");
        jButtonMudarStatusAta.setFocusable(false);
        jButtonMudarStatusAta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonMudarStatusAta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonMudarStatusAta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMudarStatusAtaActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonMudarStatusAta);

        jButtonBuscarAta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/buscar.png"))); // NOI18N
        jButtonBuscarAta.setToolTipText("Consultar Ata");
        jButtonBuscarAta.setFocusable(false);
        jButtonBuscarAta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonBuscarAta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonBuscarAta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarAtaActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonBuscarAta);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sair.png"))); // NOI18N
        jButtonSair.setText("SAIR");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jPanel2.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logo.png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 40, 480, 280);

        jLabelCoordenador.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jLabelCoordenador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCoordenador.setText("BEM VINDO, COORDENADOR!");
        jPanel2.add(jLabelCoordenador);
        jLabelCoordenador.setBounds(0, 10, 560, 23);

        jMenuGerenciar.setText("Gerenciar");

        jMenuItemGerenciarGrupos.setText("Grupos");
        jMenuItemGerenciarGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGerenciarGruposActionPerformed(evt);
            }
        });
        jMenuGerenciar.add(jMenuItemGerenciarGrupos);

        jMenuItemGerenciarServidores.setText("Servidores");
        jMenuItemGerenciarServidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGerenciarServidoresActionPerformed(evt);
            }
        });
        jMenuGerenciar.add(jMenuItemGerenciarServidores);

        jMenuItemGerenciarReunioes.setText("Reuniões");
        jMenuItemGerenciarReunioes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGerenciarReunioesActionPerformed(evt);
            }
        });
        jMenuGerenciar.add(jMenuItemGerenciarReunioes);

        jMenuItem1.setText("Alunos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuGerenciar.add(jMenuItem1);

        jMenuBar1.add(jMenuGerenciar);

        jMenuATAs.setText("ATAs");

        jMenuItemMudarStatusAta.setText("Mudar Status da ATA");
        jMenuItemMudarStatusAta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMudarStatusAtaActionPerformed(evt);
            }
        });
        jMenuATAs.add(jMenuItemMudarStatusAta);

        jMenuItemConsultaAta.setText("Consultar ATA");
        jMenuItemConsultaAta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaAtaActionPerformed(evt);
            }
        });
        jMenuATAs.add(jMenuItemConsultaAta);

        jMenuItemRedigirAta.setText("Redigir ATA");
        jMenuItemRedigirAta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRedigirAtaActionPerformed(evt);
            }
        });
        jMenuATAs.add(jMenuItemRedigirAta);

        jMenuBar1.add(jMenuATAs);

        jMenuSobre.setText("Sobre");
        jMenuSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSobreMouseClicked(evt);
            }
        });
        jMenuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSobreActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                .addComponent(jButtonSair))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemGerenciarServidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGerenciarServidoresActionPerformed
        new GerenciarServidoresGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemGerenciarServidoresActionPerformed

    private void jMenuItemGerenciarGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGerenciarGruposActionPerformed
        new GerenciarGruposGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemGerenciarGruposActionPerformed

    private void jButtonGerenciarGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerenciarGruposActionPerformed
        new GerenciarGruposGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonGerenciarGruposActionPerformed

    private void jButtonGerenciarServidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerenciarServidoresActionPerformed
        new GerenciarServidoresGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonGerenciarServidoresActionPerformed

    private void jMenuSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSobreMouseClicked
        JOptionPane.showMessageDialog(this, "Desenvolvido por World Systems"
                + "\nDesenvolvedores:"
                + "\nHernane Marcos de Faria Júnior (tiaocarreiro99@gmail.com)"
                + "\nIgor Ribeiro da Silva (igorrs704@hotmail.com)"
                + "\nAlunos do Curso Técnico Integrado em Informática III - IFMG Campus Formiga");
    }//GEN-LAST:event_jMenuSobreMouseClicked

    private void jMenuItemGerenciarReunioesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGerenciarReunioesActionPerformed
        new GerenciarReunioesGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemGerenciarReunioesActionPerformed

    private void jMenuItemMudarStatusAtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMudarStatusAtaActionPerformed
        new MudarStatusAtaGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemMudarStatusAtaActionPerformed

    private void jButtonGerenciarReunioesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerenciarReunioesActionPerformed
        new GerenciarReunioesGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonGerenciarReunioesActionPerformed

    private void jButtonMudarStatusAtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMudarStatusAtaActionPerformed
        new MudarStatusAtaGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonMudarStatusAtaActionPerformed

    private void jButtonGerenciarAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerenciarAlunosActionPerformed
        new GerenciarAlunosGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonGerenciarAlunosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new GerenciarAlunosGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemRedigirAtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRedigirAtaActionPerformed
        new RedigirAtaGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemRedigirAtaActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        new LoginGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jMenuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSobreActionPerformed

    }//GEN-LAST:event_jMenuSobreActionPerformed

    private void jButtonBuscarAtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarAtaActionPerformed
        new ConsultarAtaGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonBuscarAtaActionPerformed

    private void jMenuItemConsultaAtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaAtaActionPerformed
        new ConsultarAtaGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemConsultaAtaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarAta;
    private javax.swing.JButton jButtonGerenciarAlunos;
    private javax.swing.JButton jButtonGerenciarGrupos;
    private javax.swing.JButton jButtonGerenciarReunioes;
    private javax.swing.JButton jButtonGerenciarServidores;
    private javax.swing.JButton jButtonMudarStatusAta;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCoordenador;
    private javax.swing.JMenu jMenuATAs;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuGerenciar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemConsultaAta;
    private javax.swing.JMenuItem jMenuItemGerenciarGrupos;
    private javax.swing.JMenuItem jMenuItemGerenciarReunioes;
    private javax.swing.JMenuItem jMenuItemGerenciarServidores;
    private javax.swing.JMenuItem jMenuItemMudarStatusAta;
    private javax.swing.JMenuItem jMenuItemRedigirAta;
    private javax.swing.JMenu jMenuSobre;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables

}
