package gerenciadorreunioes.modelo;
// Generated 16/09/2016 10:50:07 by Hibernate Tools 4.3.1

/**
 * AlunoGrupo generated by hbm2java
 */
public class AlunoGrupo implements java.io.Serializable {

    private Integer codigo;
    private Aluno aluno;
    private Grupo grupo;

    public AlunoGrupo() {
    }

    public AlunoGrupo(Aluno aluno, Grupo grupo) {
        this.aluno = aluno;
        this.grupo = grupo;
    }

    public Integer getCodigo() {
        return this.codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public Aluno getAluno() {
        return this.aluno;
    }

    public void setAluno(Aluno aluno) {
        this.aluno = aluno;
    }

    public Grupo getGrupo() {
        return this.grupo;
    }

    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }

}
