package gerenciadorreunioes.modelo;
// Generated 16/09/2016 10:50:07 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Aluno generated by hbm2java
 */
public class Aluno implements java.io.Serializable {

    private String matricula;
    private String nome;
    private String email;
    private Set alunoGrupos = new HashSet(0);

    public Aluno() {
    }

    public Aluno(String matricula, String nome, String email) {
        this.matricula = matricula;
        this.nome = nome;
        this.email = email;
    }

    public Aluno(String matricula, String nome, String email, Set alunoGrupos) {
        this.matricula = matricula;
        this.nome = nome;
        this.email = email;
        this.alunoGrupos = alunoGrupos;
    }

    public String getMatricula() {
        return matricula;
    }

    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Set getAlunoGrupos() {
        return alunoGrupos;
    }

    public void setAlunoGrupos(Set alunoGrupos) {
        this.alunoGrupos = alunoGrupos;
    }

}
