package gerenciadorreunioes.modelo;
// Generated 16/09/2016 10:50:07 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Ata generated by hbm2java
 */
public class Ata implements java.io.Serializable {

    private Integer codigo;
    private Reuniao reuniao;
    private String status;
    private Set pautas = new HashSet(0);

    public Ata() {
    }

    public Ata(Reuniao reuniao, String status) {
        this.reuniao = reuniao;
        this.status = status;
    }

    public Ata(Reuniao reuniao, String status, Set pautas) {
        this.reuniao = reuniao;
        this.status = status;
        this.pautas = pautas;
    }

    public void setReuniao(Reuniao reuniao) {
        this.reuniao = reuniao;
    }

    public Set getPautas() {
        return this.pautas;
    }

    public void setPautas(Set pautas) {
        this.pautas = pautas;
    }

    public Integer getCodigo() {
        return codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

}
