package gerenciadorreunioes.modelo;
// Generated 16/09/2016 10:50:07 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Grupo generated by hbm2java
 */
public class Grupo implements java.io.Serializable {

    private Integer codigo;
    private String nome;
    private String descricao;
    private String siapeCoordenador;
    private Set servidorGrupos = new HashSet(0);
    private Set alunoGrupos = new HashSet(0);
    private Set reuniaos = new HashSet(0);

    public Grupo() {
    }

    public Grupo(String nome, String siapeCoordenador) {
        this.nome = nome;
        this.siapeCoordenador = siapeCoordenador;
    }

    public Grupo(String nome, String descricao, String siapeCoordenador, Set servidorGrupos, Set alunoGrupos, Set reuniaos) {
        this.nome = nome;
        this.descricao = descricao;
        this.siapeCoordenador = siapeCoordenador;
        this.servidorGrupos = servidorGrupos;
        this.alunoGrupos = alunoGrupos;
        this.reuniaos = reuniaos;
    }

    public Integer getCodigo() {
        return codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getDescricao() {
        return descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public String getSiapeCoordenador() {
        return siapeCoordenador;
    }

    public void setSiapeCoordenador(String siapeCoordenador) {
        this.siapeCoordenador = siapeCoordenador;
    }

    public Set getServidorGrupos() {
        return this.servidorGrupos;
    }

    public void setServidorGrupos(Set servidorGrupos) {
        this.servidorGrupos = servidorGrupos;
    }

    public Set getAlunoGrupos() {
        return this.alunoGrupos;
    }

    public void setAlunoGrupos(Set alunoGrupos) {
        this.alunoGrupos = alunoGrupos;
    }

    public Set getReuniaos() {
        return this.reuniaos;
    }

    public void setReuniaos(Set reuniaos) {
        this.reuniaos = reuniaos;
    }

}
