package gerenciadorreunioes.modelo;
// Generated 16/09/2016 10:50:07 by Hibernate Tools 4.3.1



/**
 * Pauta generated by hbm2java
 */
public class Pauta  implements java.io.Serializable {


     private Integer codigo;
     private Ata ata;
     private String titulo;
     private String definicao;

    public Pauta() {
    }
    
    public Pauta(Ata ata, String titulo) {
        this.ata = ata;
        this.titulo = titulo;
    }
    
    public Pauta(Ata ata, String titulo, String definicao) {
       this.ata = ata;
       this.titulo = titulo;
       this.definicao = definicao;
    }
    
    public Ata getAta() {
        return this.ata;
    }
    
    public void setAta(Ata ata) {
        this.ata = ata;
    }

    public Integer getCodigo() {
        return codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public String getTitulo() {
        return titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public String getDefinicao() {
        return definicao;
    }

    public void setDefinicao(String definicao) {
        this.definicao = definicao;
    }
    
}