package gerenciadorreunioes.modelo;
// Generated 16/09/2016 10:50:07 by Hibernate Tools 4.3.1



/**
 * Pauta generated by hbm2java
 */
public class Pauta  implements java.io.Serializable {


     private Integer pauCodigo;
     private Ata ata;
     private String pauTitulo;
     private String pauDefinicao;

    public Pauta() {
    }

	
    public Pauta(Ata ata, String pauTitulo) {
        this.ata = ata;
        this.pauTitulo = pauTitulo;
    }
    public Pauta(Ata ata, String pauTitulo, String pauDefinicao) {
       this.ata = ata;
       this.pauTitulo = pauTitulo;
       this.pauDefinicao = pauDefinicao;
    }
   
    public Integer getPauCodigo() {
        return this.pauCodigo;
    }
    
    public void setPauCodigo(Integer pauCodigo) {
        this.pauCodigo = pauCodigo;
    }
    public Ata getAta() {
        return this.ata;
    }
    
    public void setAta(Ata ata) {
        this.ata = ata;
    }
    public String getPauTitulo() {
        return this.pauTitulo;
    }
    
    public void setPauTitulo(String pauTitulo) {
        this.pauTitulo = pauTitulo;
    }
    public String getPauDefinicao() {
        return this.pauDefinicao;
    }
    
    public void setPauDefinicao(String pauDefinicao) {
        this.pauDefinicao = pauDefinicao;
    }




}


