package gerenciadorreunioes.modelo;
// Generated 16/09/2016 10:50:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Reuniao generated by hbm2java
 */
public class Reuniao  implements java.io.Serializable {


     private Integer codigo;
     private Grupo grupo;
     private String nome;
     private String data;
     private String horarioInicio;
     private String horarioFim;
     private String local;
     private String siapeResponsavelAta;
     private Set atas = new HashSet(0);

    public Reuniao() {
    }

	
    public Reuniao(Grupo grupo, String nome, String data) {
        this.grupo = grupo;
        this.nome = nome;
        this.data = data;
    }
    public Reuniao(Grupo grupo, String nome, String data, String horarioInicio, String horarioFim, String local, String siapeResponsavelAta, Set atas) {
       this.grupo = grupo;
       this.nome = nome;
       this.data = data;
       this.horarioInicio = horarioInicio;
       this.horarioFim = horarioFim;
       this.local = local;
       this.siapeResponsavelAta = siapeResponsavelAta;
       this.atas = atas;
    }

    public Integer getCodigo() {
        return codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }

    public String getHorarioInicio() {
        return horarioInicio;
    }

    public void setHorarioInicio(String horarioInicio) {
        this.horarioInicio = horarioInicio;
    }

    public String getHorarioFim() {
        return horarioFim;
    }

    public void setHorarioFim(String horarioFim) {
        this.horarioFim = horarioFim;
    }

    public String getLocal() {
        return local;
    }

    public void setLocal(String local) {
        this.local = local;
    }

    public String getSiapeResponsavelAta() {
        return siapeResponsavelAta;
    }

    public void setSiapeResponsavelAta(String siapeResponsavelAta) {
        this.siapeResponsavelAta = siapeResponsavelAta;
    }
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }
    public Set getAtas() {
        return this.atas;
    }
    
    public void setAtas(Set atas) {
        this.atas = atas;
    }
}