package gerenciadorreunioes.modelo;
// Generated 16/09/2016 10:50:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Reuniao generated by hbm2java
 */
public class Reuniao  implements java.io.Serializable {


     private Integer reuCodigo;
     private Grupo grupo;
     private String reuNome;
     private String reuData;
     private String reuHorarioInicio;
     private String reuHorarioFim;
     private String reuLocal;
     private String reuSiapeResponsavelAta;
     private Set atas = new HashSet(0);

    public Reuniao() {
    }

	
    public Reuniao(Grupo grupo, String reuNome, String reuData) {
        this.grupo = grupo;
        this.reuNome = reuNome;
        this.reuData = reuData;
    }
    public Reuniao(Grupo grupo, String reuNome, String reuData, String reuHorarioInicio, String reuHorarioFim, String reuLocal, String reuSiapeResponsavelAta, Set atas) {
       this.grupo = grupo;
       this.reuNome = reuNome;
       this.reuData = reuData;
       this.reuHorarioInicio = reuHorarioInicio;
       this.reuHorarioFim = reuHorarioFim;
       this.reuLocal = reuLocal;
       this.reuSiapeResponsavelAta = reuSiapeResponsavelAta;
       this.atas = atas;
    }
   
    public Integer getReuCodigo() {
        return this.reuCodigo;
    }
    
    public void setReuCodigo(Integer reuCodigo) {
        this.reuCodigo = reuCodigo;
    }
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }
    public String getReuNome() {
        return this.reuNome;
    }
    
    public void setReuNome(String reuNome) {
        this.reuNome = reuNome;
    }
    public String getReuData() {
        return this.reuData;
    }
    
    public void setReuData(String reuData) {
        this.reuData = reuData;
    }
    public String getReuHorarioInicio() {
        return this.reuHorarioInicio;
    }
    
    public void setReuHorarioInicio(String reuHorarioInicio) {
        this.reuHorarioInicio = reuHorarioInicio;
    }
    public String getReuHorarioFim() {
        return this.reuHorarioFim;
    }
    
    public void setReuHorarioFim(String reuHorarioFim) {
        this.reuHorarioFim = reuHorarioFim;
    }
    public String getReuLocal() {
        return this.reuLocal;
    }
    
    public void setReuLocal(String reuLocal) {
        this.reuLocal = reuLocal;
    }
    public String getReuSiapeResponsavelAta() {
        return this.reuSiapeResponsavelAta;
    }
    
    public void setReuSiapeResponsavelAta(String reuSiapeResponsavelAta) {
        this.reuSiapeResponsavelAta = reuSiapeResponsavelAta;
    }
    public Set getAtas() {
        return this.atas;
    }
    
    public void setAtas(Set atas) {
        this.atas = atas;
    }




}


