package gerenciadorreunioes.modelo;
// Generated 16/09/2016 10:50:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Servidor generated by hbm2java
 */
public class Servidor  implements java.io.Serializable {


     private String serSiape;
     private String serNome;
     private String serTelefone;
     private String serEmail;
     private String serSenha;
     private String serArea;
     private int serDe;
     private int serCoordenador;
     private int serResponsavelAta;
     private Set servidorGrupos = new HashSet(0);

    public Servidor() {
    }

	
    public Servidor(String serSiape, String serNome, String serTelefone, String serEmail, String serSenha, String serArea, int serDe, int serCoordenador, int serResponsavelAta) {
        this.serSiape = serSiape;
        this.serNome = serNome;
        this.serTelefone = serTelefone;
        this.serEmail = serEmail;
        this.serSenha = serSenha;
        this.serArea = serArea;
        this.serDe = serDe;
        this.serCoordenador = serCoordenador;
        this.serResponsavelAta = serResponsavelAta;
    }
    public Servidor(String serSiape, String serNome, String serTelefone, String serEmail, String serSenha, String serArea, int serDe, int serCoordenador, int serResponsavelAta, Set servidorGrupos) {
       this.serSiape = serSiape;
       this.serNome = serNome;
       this.serTelefone = serTelefone;
       this.serEmail = serEmail;
       this.serSenha = serSenha;
       this.serArea = serArea;
       this.serDe = serDe;
       this.serCoordenador = serCoordenador;
       this.serResponsavelAta = serResponsavelAta;
       this.servidorGrupos = servidorGrupos;
    }
   
    public String getSerSiape() {
        return this.serSiape;
    }
    
    public void setSerSiape(String serSiape) {
        this.serSiape = serSiape;
    }
    public String getSerNome() {
        return this.serNome;
    }
    
    public void setSerNome(String serNome) {
        this.serNome = serNome;
    }
    public String getSerTelefone() {
        return this.serTelefone;
    }
    
    public void setSerTelefone(String serTelefone) {
        this.serTelefone = serTelefone;
    }
    public String getSerEmail() {
        return this.serEmail;
    }
    
    public void setSerEmail(String serEmail) {
        this.serEmail = serEmail;
    }
    public String getSerSenha() {
        return this.serSenha;
    }
    
    public void setSerSenha(String serSenha) {
        this.serSenha = serSenha;
    }
    public String getSerArea() {
        return this.serArea;
    }
    
    public void setSerArea(String serArea) {
        this.serArea = serArea;
    }
    public int getSerDe() {
        return this.serDe;
    }
    
    public void setSerDe(int serDe) {
        this.serDe = serDe;
    }
    public int getSerCoordenador() {
        return this.serCoordenador;
    }
    
    public void setSerCoordenador(int serCoordenador) {
        this.serCoordenador = serCoordenador;
    }
    public int getSerResponsavelAta() {
        return this.serResponsavelAta;
    }
    
    public void setSerResponsavelAta(int serResponsavelAta) {
        this.serResponsavelAta = serResponsavelAta;
    }
    public Set getServidorGrupos() {
        return this.servidorGrupos;
    }
    
    public void setServidorGrupos(Set servidorGrupos) {
        this.servidorGrupos = servidorGrupos;
    }




}


