package gerenciadorreunioes.modelo;
// Generated 16/09/2016 10:50:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Servidor generated by hbm2java
 */
public class Servidor  implements java.io.Serializable {

     private String siape;
     private String nome;
     private String telefone;
     private String email;
     private String senha;
     private String area;
     private int serDe;
     private int serCoordenador;
     private int serResponsavelAta;
     private Set servidorGrupos = new HashSet(0);

    public Servidor() {
    }

	
    public Servidor(String siape, String nome, String telefone, String email, String senha, String area, int serDe, int serCoordenador, int serResponsavelAta) {
        this.siape = siape;
        this.nome = nome;
        this.telefone = telefone;
        this.email = email;
        this.senha = senha;
        this.area = area;
        this.serDe = serDe;
        this.serCoordenador = serCoordenador;
        this.serResponsavelAta = serResponsavelAta;
    }
    public Servidor(String siape, String nome, String telefone, String email, String senha, String area, int serDe, int serCoordenador, int serResponsavelAta, Set servidorGrupos) {
       this.siape = siape;
       this.nome = nome;
       this.telefone = telefone;
       this.email = email;
       this.senha = senha;
       this.area = area;
       this.serDe = serDe;
       this.serCoordenador = serCoordenador;
       this.serResponsavelAta = serResponsavelAta;
       this.servidorGrupos = servidorGrupos;
    }

    public String getSiape() {
        return siape;
    }

    public void setSiape(String siape) {
        this.siape = siape;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getTelefone() {
        return telefone;
    }

    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getSenha() {
        return senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }

    public String getArea() {
        return area;
    }

    public void setArea(String area) {
        this.area = area;
    }
    public int getSerDe() {
        return this.serDe;
    }
    
    public void setSerDe(int serDe) {
        this.serDe = serDe;
    }
    public int getSerCoordenador() {
        return this.serCoordenador;
    }
    
    public void setSerCoordenador(int serCoordenador) {
        this.serCoordenador = serCoordenador;
    }
    public int getSerResponsavelAta() {
        return this.serResponsavelAta;
    }
    
    public void setSerResponsavelAta(int serResponsavelAta) {
        this.serResponsavelAta = serResponsavelAta;
    }
    public Set getServidorGrupos() {
        return this.servidorGrupos;
    }
    
    public void setServidorGrupos(Set servidorGrupos) {
        this.servidorGrupos = servidorGrupos;
    }
}